"""API handlers for courses, lessons, homework, grading, question bank, papers and search."""

from .analytics import handle_analytics_summary
from .courses import (
    handle_course_detail,
    handle_course_members,
    handle_courses_create,
    handle_courses_join,
    handle_courses_list,
)
from .grading import (
    handle_ai_generate_questions,
    handle_ai_grade,
    handle_ai_grade_cropgpt,
    handle_ai_grade_general,
    handle_ai_grade_question,
    handle_homework_delete,
    handle_homework_grade,
    handle_homework_publish,
)
from .homework import (
    handle_homework_create,
    handle_homework_detail,
    handle_homework_list,
    handle_homework_submissions,
    handle_homework_submit,
    handle_submission_detail,
)
from .lessons import handle_lesson_detail, handle_lessons_list
from .papers import (
    handle_delete_paper,
    handle_get_paper,
    handle_get_paper_chunks,
    handle_get_paper_pdf,
    handle_list_papers,
    handle_toggle_favorite,
    handle_update_annotations,
    handle_update_tags,
    handle_upload_paper,
)
from .question_bank import (
    handle_question_bank_add,
    handle_question_bank_batch_add,
    handle_question_bank_delete,
    handle_question_bank_list,
    handle_question_bank_update,
)
from .research_results import (
    handle_create_research_result,
    handle_delete_research_result,
    handle_get_research_result,
    handle_list_research_results,
    handle_update_research_result,
)
from .research_exports import handle_export_research_artifact, handle_export_research_result
from .research_copilot import handle_paper_copilot
from .research_artifacts import (
    handle_create_research_artifact,
    handle_delete_research_artifact,
    handle_get_research_artifact,
    handle_list_research_artifacts,
    handle_regenerate_research_artifact,
    handle_update_research_artifact,
)
from .research_workspace import (
    handle_create_latex_compile_record,
    handle_create_research_project,
    handle_delete_research_project,
    handle_get_research_job,
    handle_get_research_project_links,
    handle_migrate_research_project_links,
    handle_retry_research_job,
    handle_update_research_project,
    handle_update_research_project_links,
    handle_get_latex_draft,
    handle_list_research_attachments,
    handle_delete_research_attachment,
    handle_list_latex_draft_versions,
    handle_list_latex_drafts,
    handle_list_research_projects,
    handle_save_latex_draft,
    handle_upload_research_attachment,
)
from .search import handle_import_paper, handle_search_papers
from .student_categories import (
    handle_student_categories_list,
    handle_student_category_create,
    handle_student_category_delete,
    handle_student_category_update,
    handle_student_resource_categorize,
)
from .student_resources import (
    handle_student_resource_create,
    handle_student_resource_delete,
    handle_student_resource_favorite,
    handle_student_resource_update,
    handle_student_resource_upload,
    handle_student_resources_list,
)
from .tutor import handle_tutor_profile

from .notifications import (
    handle_discussion_create,
    handle_discussion_list,
    handle_discussion_reply,
    handle_notification_create,
    handle_notification_list,
    handle_notification_mark_read,
)
from .resources import (
    handle_resource_create,
    handle_resource_delete,
    handle_resource_list,
)

__all__ = [
    "handle_analytics_summary",
    "handle_courses_list",
    "handle_courses_create",
    "handle_courses_join",
    "handle_course_detail",
    "handle_course_members",
    "handle_lessons_list",
    "handle_lesson_detail",
    "handle_homework_list",
    "handle_homework_create",
    "handle_homework_detail",
    "handle_homework_submit",
    "handle_homework_submissions",
    "handle_submission_detail",
    "handle_homework_grade",
    "handle_ai_grade",
    "handle_ai_grade_cropgpt",
    "handle_ai_grade_general",
    "handle_ai_grade_question",
    "handle_homework_publish",
    "handle_homework_delete",
    "handle_ai_generate_questions",
    "handle_question_bank_list",
    "handle_question_bank_add",
    "handle_question_bank_batch_add",
    "handle_question_bank_delete",
    "handle_question_bank_update",
    "handle_student_categories_list",
    "handle_student_category_create",
    "handle_student_category_delete",
    "handle_student_category_update",
    "handle_student_resource_categorize",
    "handle_student_resources_list",
    "handle_student_resource_create",
    "handle_student_resource_favorite",
    "handle_student_resource_delete",
    "handle_student_resource_update",
    "handle_student_resource_upload",
    "handle_tutor_profile",
    "handle_list_papers",
    "handle_upload_paper",
    "handle_get_paper",
    "handle_get_paper_chunks",
    "handle_get_paper_pdf",
    "handle_delete_paper",
    "handle_toggle_favorite",
    "handle_update_annotations",
    "handle_update_tags",
    "handle_search_papers",
    "handle_import_paper",
    "handle_list_research_results",
    "handle_create_research_result",
    "handle_get_research_result",
    "handle_delete_research_result",
    "handle_update_research_result",
    "handle_export_research_result",
    "handle_export_research_artifact",
    "handle_paper_copilot",
    "handle_list_research_projects",
    "handle_create_research_project",
    "handle_get_research_project_links",
    "handle_update_research_project_links",
    "handle_migrate_research_project_links",
    "handle_update_research_project",
    "handle_delete_research_project",
    "handle_get_research_job",
    "handle_retry_research_job",
    "handle_list_research_attachments",
    "handle_upload_research_attachment",
    "handle_delete_research_attachment",
    "handle_list_research_artifacts",
    "handle_create_research_artifact",
    "handle_get_research_artifact",
    "handle_regenerate_research_artifact",
    "handle_update_research_artifact",
    "handle_delete_research_artifact",
    "handle_list_latex_drafts",
    "handle_get_latex_draft",
    "handle_save_latex_draft",
    "handle_list_latex_draft_versions",
    "handle_create_latex_compile_record",
    # Resources
    "handle_resource_list",
    "handle_resource_create",
    "handle_resource_delete",
    # Notifications & discussions
    "handle_notification_list",
    "handle_notification_create",
    "handle_notification_mark_read",
    "handle_discussion_list",
    "handle_discussion_create",
    "handle_discussion_reply",
]
